[package]
name = "chart_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
rfd = "0.10"
csv = "1.1"
polars = { version = "0.23.0", features=["lazy", "csv-file"] }
